### ISSUE TITLE
Error while training the model

### ISSUE THREAD

**Issue by vnghia** [Walter0807/mocanet.pytorch#2]
Good morning,

Thank you for the paper, it looks really interesting and I would like to try it out. However, when I try training your model follow the tutorial in your README, this line of code 

```
python train.py --config configs/mocanet.yaml
```

will throw an error:

```
Traceback (most recent call last):
  File "/home/xana/code/mocanet.pytorch/train.py", line 111, in <module>
    train_with_config(config, opts)
  File "/home/xana/code/mocanet.pytorch/train.py", line 43, in train_with_config
    train_loader = get_dataloader("train", config)
  File "/home/xana/code/mocanet.pytorch/lib/data.py", line 31, in get_dataloader
    dataloader = DataLoader(dataset, shuffle=True,
  File "/home/xana/mambaforge/envs/ubi/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 344, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/home/xana/mambaforge/envs/ubi/lib/python3.10/site-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0
```

I put the dataset inside `data/mixamo`.

Could you provide me some insight to fix this ?

Thank you very much !

**Comment by vnghia** [comment]
Hi, I found the error, I should have run `scripts/data/preprocess.sh` beforehand. Do you think we should add a line in README ?

**Comment by Walter0807** [comment]
Great! I just updated README, thanks for your suggestion.
